name: "Reusable: Sync Epic/Subtasks"
on:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: write

    steps:
      - name: Checkout shared .github repo
        uses: actions/checkout@v4
        with:
          repository: EvidenceB/.github # replace your-org
          path: .github_shared
          ref: main

      - name: Run sync script
        uses: actions/github-script@v7
        env:
          PROJECT_NUMBER: "6"
        with:
          script: |
            const fn = require('./.github_shared/scripts/sync-subtask.js');
            await fn({ github, context, core, projectNumber: process.env.PROJECT_NUMBER });
