name: "Reusable: Sync Epic/Subtasks"
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: write

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Run sync script
        run: node ./scripts/sync-subtask.js
