name: "Reusable: Sync Epic/Subtasks"
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: write

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Run sync script via github-script
        uses: actions/github-script@v7
        with:
          script: |
            const fn = require('./.github/scripts/sync-subtask.js');
            await fn({ github, context, core });
